package net.alexanderlyons.gastrackerapp;

import com.jjoe64.graphview.series.DataPoint;

import java.util.Date;

//import io.realm.RealmObject;
//import io.realm.annotations.PrimaryKey;

/**
 * Created by PyroticBlaziken on 3/28/2015.
 */
public class Trip /*extends RealmObject*/ {

    //@PrimaryKey
    public int recordID;
    public Date time;
    public double miles;
    public double pricePerGallon;
    public double gallonsPurchased;
    public int carID;

    // Standard Getters & Setters generated by Android Studio
    public int getRecordID() {
        return recordID;
    }

    public void setRecordID(int recordID) {
        this.recordID = recordID;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public double getMiles() {
        return miles;
    }

    public void setMiles(double miles) {
        this.miles = miles;
    }

    public double getPricePerGallon() {
        return pricePerGallon;
    }

    public void setPricePerGallon(double pricePerGallon) {
        this.pricePerGallon = pricePerGallon;
    }

    public double getGallonsPurchased() {
        return gallonsPurchased;
    }

    public void setGallonsPurchased(double gallonsPurchased) {
        this.gallonsPurchased = gallonsPurchased;
    }

    public int getCarID() {
        return carID;
    }

    public void setCarID(int carID) {
        this.carID = carID;
    }


    public double costPerMile() {
        return this.totalPurchasePrice() / miles;
    }

    public double milesPerGallon() {
        return miles / gallonsPurchased;
    }

    public double totalPurchasePrice() {
        return pricePerGallon * gallonsPurchased;
    }

    public DataPoint toTestDataPoint() {
        return new DataPoint(recordID, milesPerGallon());
    }
}
